# Site settings
title: Toddler 👶 inspired reward transition
description: >
  Toodler inspired reward transition beats other reward algorithms in goal oriented RL.
baseurl: ""
url: "https://frankpark.github.io/Toddler-Inspired-Reward-Transition/" # the base hostname & protocol for your site
github_username: Frankpark

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Default values
# defaults:
#   -
#     scope:
#       path: ""
#       type: "posts"
#     values:
#       layout: "post"
#       author: "Your Name"

# Exclusions
exclude:
  - node_modules
  - vendor/bundle
  - Gemfile.lock
  - .jekyll-cache
  - .jekyll-metadata

